language: node_js
node_js:
  - '8'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build

before_deploy: cp dist/index.html dist/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
